version: "3"
volumes:
  elixir-redis:
  elixir-postgres:
  elixir-adminer:
networks:
  im-net:
  im-internal-net:
    internal: true
services:
  elixir-app:
    build:
      context: .
      dockerfile: ./Dockerfile   
    volumes:
      - ../src:/elixir-app/src
      - ../config.json:/elixir-app/config.json
    networks:
      - im-net
      - im-internal-net
  elixir-redis:
    image: redis
    volumes:
      - elixir-redis:/data
    expose:
      - 6379
    ports:
      - 6379:6379      
    restart: unless-stopped
    networks:
      - im-net
      - im-internal-net
  elixir-postgres:
    image: postgres
    volumes:
      - elixir-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - 5432
    ports:
      - 5432:5432      
    restart: unless-stopped
    networks:
      - im-net
      - im-internal-net
  elixir-adminer:
    image: adminer
    volumes:
      - elixir-adminer:/var/lib/postgresql/data
    environment:
      ADMINER_DEFAULT_SERVER: elixir-postgres
      ADMINER_DEFAULT_USER: postgres
      ADMINER_DEFAULT_PASSWORD: postgres
      ADMINER_DEFAULT_TYPE: postgresql
    expose:
      - 8080
    ports:
      - 8080:8080      
    restart: unless-stopped
    networks:
      - im-net
      - im-internal-net
